name: gallardo_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
  - assets/img_1.jpg
  - assets/img_2.jpg
  - assets/img_3.jpg
  - assets/img_4.png
  - assets/img_5.jpg
